name: fyvent
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.12.0+1
  url_launcher: ^5.0.1
  google_sign_in: ^4.0.0
  google_maps_flutter: ^0.3.0+2
  firebase_auth: ^0.8.1+3
  cloud_firestore: ^0.9.5+2
  permission_handler: ^2.2.0
  flutter_spinkit: "^3.1.0"


dev_dependencies:
  flutter_launcher_icons: ^0.7.0
  flutter_test:
    sdk: flutter
  test: ^1.5.1
  image_test_utils: ^1.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Greycliff
      fonts:
        - asset: assets/fonts/GreycliffCF-DemiBold.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 600
  assets:
    - assets/images/splash.jpg
    - assets/images/logo-light.png
    - assets/images/logo-dark.png
    - assets/images/logo-color.png
    - assets/images/google-logo.png
